"use client";

import { useActionState, useState } from "react";
import { regenerateSectionAction } from "@/app/projects/[id]/packs/actions";
import type { FormState } from "@/lib/forms";
import { cn } from "@/lib/utils";
import {
  BA_SECTIONS,
  FA_SECTIONS,
  isNarrativeSection,
} from "@/lib/pack-builders/types";
import { Button, Card, CardBody, CardHeader, CardTitle } from "@/components/ui";
import { SubmitButton } from "@/components/ui/submit-button";

type PreviewTab = "rendered" | "markdown" | "json";

/**
 * Pack preview.
 *
 * The rendered tab shows the exact HTML that gets exported — same markup, same
 * stylesheet — inside a sandboxed iframe. Previewing a re-styled approximation
 * would defeat the purpose: the point is to see what the client will see.
 */
export function PackPreview({
  projectId,
  pack,
}: {
  projectId: string;
  pack: {
    id: string;
    mode: "BA" | "FA";
    title: string;
    html: string;
    markdown: string;
    json: string;
  };
}) {
  const [tab, setTab] = useState<PreviewTab>("rendered");
  const sections = pack.mode === "BA" ? BA_SECTIONS : FA_SECTIONS;

  return (
    <div className="grid gap-5 lg:grid-cols-[1fr_16rem]">
      <Card className="overflow-hidden">
        <CardHeader>
          <CardTitle>{pack.title}</CardTitle>
          <div className="flex gap-1">
            {(["rendered", "markdown", "json"] as PreviewTab[]).map((key) => (
              <button
                key={key}
                type="button"
                onClick={() => setTab(key)}
                className={cn(
                  "rounded px-2 py-1 text-xs capitalize transition-colors",
                  tab === key
                    ? "bg-accent-soft font-medium text-accent"
                    : "text-ink-muted hover:bg-surface-muted hover:text-ink",
                )}
              >
                {key}
              </button>
            ))}
          </div>
        </CardHeader>

        {tab === "rendered" ? (
          <iframe
            title={`${pack.title} preview`}
            srcDoc={pack.html}
            // The pack HTML is generated by our own renderer, but it embeds
            // analyst-authored text. Sandboxing costs nothing and removes the
            // whole class of concern.
            sandbox=""
            className="h-[70vh] w-full border-0 bg-white"
          />
        ) : (
          <pre className="h-[70vh] overflow-auto bg-surface-muted px-5 py-4 font-mono text-xs leading-relaxed text-ink-soft">
            {tab === "markdown" ? pack.markdown : pack.json}
          </pre>
        )}
      </Card>

      <div className="space-y-4">
        <Card>
          <CardHeader>
            <CardTitle>Sections</CardTitle>
          </CardHeader>
          <CardBody className="px-3 py-2">
            <ul className="space-y-0.5">
              {sections.map((section) => (
                <li key={section.key}>
                  <SectionRow
                    projectId={projectId}
                    packId={pack.id}
                    sectionKey={section.key}
                    label={section.label}
                  />
                </li>
              ))}
            </ul>
          </CardBody>
        </Card>

        <p className="text-xs leading-relaxed text-ink-faint">
          Sections marked <span className="text-accent">written</span> are prose from
          the model — regenerating rewrites just that section. The rest are assembled
          from your entities, so regenerating them simply re-reads the current model.
        </p>
      </div>
    </div>
  );
}

function SectionRow({
  projectId,
  packId,
  sectionKey,
  label,
}: {
  projectId: string;
  packId: string;
  sectionKey: string;
  label: string;
}) {
  // The BA pack merges assumptions and constraints into one section; map it
  // back to a real narrative key so the button behaves sensibly.
  const target = sectionKey === "assumptionsConstraints" ? "assumptions" : sectionKey;
  const narrative = isNarrativeSection(target);

  const [state, formAction] = useActionState<FormState, FormData>(
    regenerateSectionAction.bind(null, projectId, packId, target),
    null,
  );

  return (
    <form action={formAction} className="group flex items-center gap-2 rounded px-2 py-1 hover:bg-surface-muted">
      <span className="min-w-0 flex-1 truncate text-xs text-ink-soft">{label}</span>
      <span
        className={cn(
          "shrink-0 text-[10px] uppercase tracking-wide",
          narrative ? "text-accent" : "text-ink-faint",
        )}
        title={
          narrative
            ? "Prose written by the model"
            : "Assembled from your entities — no AI involved"
        }
      >
        {narrative ? "written" : "model"}
      </span>
      <SubmitButton
        size="sm"
        variant="ghost"
        pendingLabel="…"
        className="shrink-0 opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100"
      >
        ↻
      </SubmitButton>
      {state?.message ? (
        <span
          className={cn(
            "absolute right-4 text-[10px]",
            state.ok ? "text-positive" : "text-critical",
          )}
        >
          {state.ok ? "done" : "failed"}
        </span>
      ) : null}
    </form>
  );
}

/** Copy-to-clipboard for the markdown, used by the export screen too. */
export function CopyButton({ value, label }: { value: string; label: string }) {
  const [copied, setCopied] = useState(false);

  return (
    <Button
      onClick={async () => {
        await navigator.clipboard.writeText(value);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      }}
    >
      {copied ? "Copied" : label}
    </Button>
  );
}
