import "server-only";
import { prisma } from "@/lib/db/client";
import { loadProjectModel } from "@/lib/db/queries";
import { AI_EFFORT, isAiConfigured } from "@/lib/ai/client";
import { runStructuredJob } from "@/lib/ai/runner";
import { baNarrativeSchema, faNarrativeSchema } from "@/lib/ai/schemas";
import { packNarrativePrompt } from "@/lib/prompts/pack-narrative";
import {
  assembleBaPack,
  assembleFaPack,
} from "@/lib/pack-builders/assemble";
import { renderPackMarkdown } from "@/lib/pack-builders/markdown";
import { renderPackHtml } from "@/lib/pack-builders/html";
import {
  baPackSchema,
  faPackSchema,
  isNarrativeSection,
  type NarrativeSection,
} from "@/lib/pack-builders/types";
import type { BaNarrative, FaNarrative } from "@/lib/ai/schemas";

/**
 * Regenerate one section of an existing pack, leaving the rest untouched.
 *
 * The two kinds of section behave differently, and the UI says so:
 *
 * - List sections (requirements, rules, use cases, criteria, dependencies,
 *   risks) are assembled from entities. "Regenerating" them means re-reading
 *   the model — no AI call, no cost, and the result is deterministic. This is
 *   what you use after editing a requirement.
 *
 * - Narrative sections (overview, business problem, scope, functional scope,
 *   data/validation, non-functional, open questions) are written by the model.
 *   Regenerating one re-runs the narrative job and splices in only that field,
 *   so a section the analyst is happy with is never silently rewritten.
 */

export async function regeneratePackSection(
  projectId: string,
  packId: string,
  section: string,
): Promise<{ refreshedFromModel: boolean }> {
  const row = await prisma.packOutput.findUnique({ where: { id: packId } });
  if (!row || row.projectId !== projectId) throw new Error("Pack not found");

  const model = await loadProjectModel(projectId);
  if (!model) throw new Error("Project not found");

  const isBa = row.mode === "BA";
  const parsed = isBa
    ? baPackSchema.safeParse(JSON.parse(row.jsonContent))
    : faPackSchema.safeParse(JSON.parse(row.jsonContent));

  if (!parsed.success) {
    throw new Error(
      "This pack was generated by an older version of the app and cannot be edited section by section. Generate a fresh pack.",
    );
  }

  const existing = parsed.data;
  const wantsNarrative = isNarrativeSection(section);

  // Start from the narrative already in the pack. Only the requested field is
  // replaced, so regenerating "scope" cannot disturb "businessProblem".
  let narrative = extractNarrative(existing, isBa);

  if (wantsNarrative) {
    if (!isAiConfigured()) {
      throw new Error(
        "Narrative sections need AI. Set ANTHROPIC_API_KEY to regenerate this section, or edit it after export.",
      );
    }

    const input = {
      mode: existing.meta.mode,
      goals: model.businessGoals.map((g) => g.title),
      stakeholders: model.stakeholders.map((s) => s.name),
      actors: model.actors.map((a) => a.name),
      rules: model.businessRules.map((r) => r.ruleText),
      requirements: model.requirements.map((r) => ({
        ref: r.ref,
        title: r.title,
        type: r.requirementType,
        priority: r.priority,
      })),
      useCases: model.useCases.map((u) => ({
        ref: u.ref,
        title: u.title,
        scopeLevel: u.scopeLevel,
      })),
      assumptions: registerText(model, "assumption"),
      constraints: registerText(model, "constraint"),
      risks: registerText(model, "risk"),
      unreviewedCount: model.insights.filter((i) => i.status === "pending").length,
    };

    const fresh = isBa
      ? (
          await runStructuredJob({
            projectId,
            job: "pack_generation",
            prompt: packNarrativePrompt,
            context: { project: model.project, mode: existing.meta.mode },
            input,
            schema: baNarrativeSchema,
            inputEntityIds: model.requirements.map((r) => r.id),
            effort: AI_EFFORT.narrative,
          })
        ).data
      : (
          await runStructuredJob({
            projectId,
            job: "pack_generation",
            prompt: packNarrativePrompt,
            context: { project: model.project, mode: existing.meta.mode },
            input,
            schema: faNarrativeSchema,
            inputEntityIds: model.requirements.map((r) => r.id),
            effort: AI_EFFORT.narrative,
          })
        ).data;

    narrative = spliceSection(narrative, fresh, section as NarrativeSection);
  }

  const meta = {
    ...existing.meta,
    generatedAt: new Date().toISOString(),
    narrativeSource: wantsNarrative
      ? ("ai" as const)
      : existing.meta.narrativeSource,
  };

  const rebuilt = isBa
    ? assembleBaPack({ model, meta, narrative: narrative as BaNarrative })
    : assembleFaPack({ model, meta, narrative: narrative as FaNarrative });

  await prisma.packOutput.update({
    where: { id: packId },
    data: {
      jsonContent: JSON.stringify(rebuilt, null, 2),
      markdownContent: renderPackMarkdown(rebuilt),
      htmlContent: renderPackHtml(rebuilt),
    },
  });

  return { refreshedFromModel: !wantsNarrative };
}

function extractNarrative(
  pack: ReturnType<typeof baPackSchema.parse> | ReturnType<typeof faPackSchema.parse>,
  isBa: boolean,
): BaNarrative | FaNarrative {
  if (isBa) {
    const ba = pack as ReturnType<typeof baPackSchema.parse>;
    return {
      overview: ba.overview,
      businessProblem: ba.businessProblem,
      scope: ba.scope,
      openQuestions: ba.openQuestions,
    };
  }
  const fa = pack as ReturnType<typeof faPackSchema.parse>;
  return {
    overview: fa.overview,
    functionalScope: fa.functionalScope,
    dataValidationConsiderations: fa.dataValidationConsiderations,
    nonFunctionalConsiderations: fa.nonFunctionalConsiderations,
    openQuestions: fa.openQuestions,
  };
}

function spliceSection<T extends BaNarrative | FaNarrative>(
  current: T,
  fresh: T,
  section: NarrativeSection,
): T {
  if (!(section in fresh)) return current;
  return { ...current, [section]: fresh[section as keyof T] };
}

function registerText(
  model: Awaited<ReturnType<typeof loadProjectModel>>,
  type: string,
): string[] {
  if (!model) return [];
  return model.insights
    .filter((i) => i.insightType === type && i.status !== "dismissed")
    .map((i) => i.normalizedText);
}
